addpath("D:\NYNGroup\eeglab2023.1\")
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%% Generate PPvalidation .set data (preprocessed)
% CONFIGURATION VARIABLES
type_of_pp  = 'pp_validation'
dataPath    = 'D:\shared_git\MaestriaThesis\NeuroSenseDatabase';
ggERP       = true;                    
PSD         = false;
ERSP_ITPC   = true;
DipClus     = false;
savejpg     = false;
savemat     = true;
saveStudy   = true;
recompute = true;
plot_clustmetrics = false;
StudyInfo  = {};
outPath    =  fullfile('D:\shared_git\MaestriaThesis\results', type_of_pp, 'eeglabStudy');
listStimuli = {'Air','Air1','Air2','Air3','Air4',...
               'Vib','Vib1','Vib2','Vib3','Vib4',...
               'Car','Car1','Car2','Car3','Car4'};
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%

parfor type = 1:15
    tstimul = listStimuli{type};
    StudyInfo = getStudyInfo(dataPath,tstimul,type_of_pp);
    DataStruct = getDataFromStudy(StudyInfo, type_of_pp, tstimul ...
    ,'ggERP'       , ggERP ... 
    ,'PSD'         , PSD ...
    ,'ERSP_ITPC'   , ERSP_ITPC ...
    ,'DipClus'     , DipClus ...
    ,'savejpg'     , savejpg...
    ,'savemat'     , savemat...
    ,'fignum'      , type ...
    ,'recompute'   , recompute ...
    ,'saveStudy'   , saveStudy ...
    ,'plot_clustmetrics', plot_clustmetrics...
    ,'numclust', 11);
     %'outPath'     , outPath ...
end
